sonar.projectKey=poc-observability-security
sonar.projectName=POC Observability + Security
sonar.sources=.
sonar.sourceEncoding=UTF-8

# IaC/Build-Ausnahmen (spart Zeit & Lärm)
sonar.exclusions=**/.terraform/**,**/*.tfstate*,**/charts/**,**/helm/**,**/vendor/**,**/node_modules/**,**/.venv/**
